// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhptpfinjzkvrzjaqpax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlocHRwZmluanprdnJ6amFxcGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDgxMDcsImV4cCI6MjA2NjI4NDEwN30.8XXjN0hOAmiW_zdMboqgvOM9HXzLypohhNltRHIDCOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);